apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-exec-probe-demo-fail
spec:
  selector:
    matchLabels:
      app: k8s-exec-probe-demo-fail
  template:
    metadata:
      labels:
        app: k8s-exec-probe-demo-fail
    spec:
      containers:
      - name: k8s-exec-probe-demo
        image: k3d-registry.localhost:5000/k8s-exec-probe-demo
        imagePullPolicy: Always
        args:
          - "60"
        readinessProbe:
          exec:
            command:
              - "./readiness.sh"
              - "/tmp/health.txt"
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - "./liveness.sh"
              - "10"
              - "/tmp/health.txt"
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
